PORT = 8080
CONFIG = config.yaml

run-none:
	python3 -W ignore auth_none.py -c $(shell pwd)/$(CONFIG) -p $(PORT)

run-url-token:
	python3 -W ignore auth_url_token.py -c $(shell pwd)/$(CONFIG) -p $(PORT)